### ISSUE TITLE
if文のコードの記述についてです！

### ISSUE THREAD

**Issue by krystalmm** [akasatan/PFescape#27]
めいてぃーお疲れ様です！
コントローラのコードを見ててリファクタリングできそうかもと思った部分共有させて頂きます！（コードレビューってissueに書くので合ってますかね？？）

if文なんですけど、例えば、

if hoge = 0
  puts 'hoge'
end

みたいにelseがない時は、

return unless hoge = 0
 
puts 'hoge'

のようにreturn + ifかunless を使うと、elseの時（ifの条件に一致しない時）はreturn してくれるので、処理が若干早くなるかもです！！行数は変わらないんですけど、rubocop使ってたらこの記述に変えろって言われます！笑
（あと、return 文の後は空行がいるみたいです！！）

ご確認よろしくお願い致します！

**Comment by akasatan** [comment]
ありがとうございます！確認して修正します～

本当はcloneしてきて修正してプルリクを送れるようにしたいんですけど、どうやって設定するんだろう・・・と考え中です
(うちうちなので、SSH鍵をDMしてもらって登録すればプルリク送れるのでそれでもいいかなーとも思ってますが、もっといいやり方調べ中です）

**Comment by akasatan** [comment]
なんか共同編集者っているのがあったので招待してみました！
ブランチ保護ルールだけ付けてみたので、もしかしたらcloneからのpushできるかもしれないです・・・！

**Comment by krystalmm** [comment]
ありがとうございます！！
やり方わかんないですよね。。
共同編集者に入っちゃって大丈夫なんですか！！

**Comment by akasatan** [comment]
大丈夫だと思います！
Adminに設定した人以外はmasterに承認がないとマージ出来ない設定があって、それを付け加えれば安全？だと思います！

**Comment by krystalmm** [comment]
そうなんですね！
ありがとうございます！！
プルリク確認させて頂きます！！

**Comment by akasatan** [comment]
マージが上手くいっていませんが、修正は完了したのでissueは閉じます！
